'''
plantuml files are generated through a logger
'''

import logging

logging.basicConfig(filename='autouml.log', level=logging.INFO, format='%(message)s')
logging.info("/' generated by autouml '/")
