'''
plantuml files are generated through a logger
'''

import logging
import logging.handlers
import atexit
import plantuml

pUML = plantuml.PlantUML()

logger = logging.getLogger('autouml')

__handler1 = logging.handlers.RotatingFileHandler('autouml.log', backupCount=1)
__handler2 = logging.FileHandler('autouml.log')

__log_format = logging.Formatter('%(message)s')

__handler1.setFormatter(__log_format)
__handler2.setFormatter(__log_format)


__handler1.doRollover()
logger.addHandler(__handler1)
# logger.addHandler(__handler2)

logger.setLevel(logging.INFO)


logger.info("/' Log generated by autouml '/")
logger.info('''@startuml
skinparam handwritten true''')


def closeuml():

    logger.info("@enduml")
    logger.debug("/' generating image at autouml.png'/")
    pUML.processes_file('autouml.log', outfile='autouml.png')

atexit.register(closeuml)
